/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityLogEntry {
  'action' : string,
  'userId' : Principal,
  'timestamp' : Time,
  'details' : string,
}
export type AppRole = { 'Staff' : null } |
  { 'Admin' : null } |
  { 'Karigar' : null };
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface BlockUserRequest {
  'user' : Principal,
  'reason' : [] | [string],
}
export interface BulkOrderUpdate {
  'isReturnedFromDelivered' : [] | [boolean],
  'orderNos' : Array<string>,
  'newStatus' : string,
}
export interface DesignImageMapping {
  'createdAt' : Time,
  'createdBy' : Principal,
  'genericName' : string,
  'image' : ExternalBlob,
  'designCode' : string,
}
export type ExternalBlob = Uint8Array;
export interface HallmarkReturnRequest {
  'actionType' : { 'update_status' : null } |
    { 'return_hallmark' : null },
  'orderNos' : Array<string>,
}
export interface HealthCheckResponse {
  'status' : string,
  'canisterId' : string,
}
export interface Karigar { 'name' : string, 'isActive' : boolean }
export interface MasterDesignEntry {
  'isActive' : boolean,
  'karigarName' : string,
  'genericName' : string,
}
export interface PartialFulfillmentQty {
  'suppliedQty' : bigint,
  'orderNo' : string,
}
export interface PartialFulfillmentRequest {
  'entries' : Array<PartialFulfillmentQty>,
}
export interface PersistentKarigar { 'name' : string, 'isActive' : boolean }
export interface PersistentOrder {
  'qty' : bigint,
  'weight' : [] | [number],
  'status' : string,
  'createdAt' : Time,
  'size' : [] | [number],
  'orderType' : string,
  'isReturnedFromDelivered' : boolean,
  'orderNo' : string,
  'isCustomerOrder' : boolean,
  'karigarName' : string,
  'genericName' : string,
  'designCode' : string,
  'uploadDate' : Time,
  'remarks' : string,
}
export type Time = bigint;
export interface UnmappedOrderEntry {
  'qty' : bigint,
  'weight' : [] | [number],
  'createdAt' : Time,
  'size' : [] | [number],
  'orderType' : string,
  'orderNo' : string,
  'isCustomerOrder' : boolean,
  'designCode' : string,
  'uploadDate' : Time,
  'remarks' : string,
}
export interface UpdateOrderTotalSuppliedRequest {
  'orderNo' : string,
  'newTotalSupplied' : bigint,
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'isCreated' : boolean,
  'appRole' : AppRole,
  'name' : string,
  'karigarName' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'blockUser' : ActorMethod<[BlockUserRequest], undefined>,
  'bulkMarkOrdersAsDelivered' : ActorMethod<[Array<string>], undefined>,
  'bulkUpdateOrderStatus' : ActorMethod<[BulkOrderUpdate], undefined>,
  'createKarigar' : ActorMethod<[Karigar], undefined>,
  'createUserProfile' : ActorMethod<[Principal, UserProfile], undefined>,
  'deleteKarigarByName' : ActorMethod<[string], undefined>,
  'getActiveOrdersForKarigar' : ActorMethod<[], Array<PersistentOrder>>,
  'getActivityLog' : ActorMethod<[], Array<ActivityLogEntry>>,
  'getAdminDesignImageMappings' : ActorMethod<
    [],
    Array<[DesignImageMapping, ExternalBlob]>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDesignImageMappings' : ActorMethod<[], Array<DesignImageMapping>>,
  'getMasterDesigns' : ActorMethod<[], Array<[string, MasterDesignEntry]>>,
  'getOrders' : ActorMethod<[], Array<PersistentOrder>>,
  'getUnmappedDesignCodes' : ActorMethod<[], Array<UnmappedOrderEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'handleHallmarkReturns' : ActorMethod<[HallmarkReturnRequest], undefined>,
  'healthCheck' : ActorMethod<[], HealthCheckResponse>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'isUserBlocked' : ActorMethod<[Principal], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'listDistinctKarigars' : ActorMethod<[], Array<PersistentKarigar>>,
  'listKarigars' : ActorMethod<[], Array<PersistentKarigar>>,
  'listKarigarsNames' : ActorMethod<[], Array<string>>,
  'listUserProfiles' : ActorMethod<[], Array<UserProfile>>,
  'markOrderAsDelivered' : ActorMethod<[string], undefined>,
  'processPartialFulfillment' : ActorMethod<
    [PartialFulfillmentRequest],
    undefined
  >,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveDesignImageMappings' : ActorMethod<
    [Array<DesignImageMapping>],
    Array<DesignImageMapping>
  >,
  'saveMasterDesigns' : ActorMethod<
    [Array<[string, MasterDesignEntry]>],
    undefined
  >,
  'setActiveFlagForMasterDesign' : ActorMethod<[string, boolean], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'unblockUser' : ActorMethod<[Principal], undefined>,
  'updateOrderTotalSupplied' : ActorMethod<
    [UpdateOrderTotalSuppliedRequest],
    undefined
  >,
  'updateOrdersForNewKarigar' : ActorMethod<[string, string], undefined>,
  'uploadParsedOrders' : ActorMethod<[Array<PersistentOrder>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];