/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AppRole = { 'Staff' : null } |
  { 'Admin' : null } |
  { 'Karigar' : null };
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type DesignCode = string;
export interface HealthCheckResponse {
  'status' : string,
  'canisterId' : string,
}
export interface MasterDesignEntry {
  'isActive' : boolean,
  'karigarName' : string,
  'genericName' : string,
}
export interface Order {
  'qty' : bigint,
  'weight' : number,
  'status' : string,
  'createdAt' : Time,
  'size' : number,
  'orderType' : string,
  'orderNo' : string,
  'isCustomerOrder' : boolean,
  'karigarName' : string,
  'genericName' : string,
  'designCode' : string,
  'uploadDate' : Time,
  'remarks' : string,
}
export type Time = bigint;
export interface UnmappedOrderEntry {
  'qty' : bigint,
  'weight' : number,
  'createdAt' : Time,
  'size' : number,
  'orderType' : string,
  'orderNo' : string,
  'isCustomerOrder' : boolean,
  'designCode' : string,
  'uploadDate' : Time,
  'remarks' : string,
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'appRole' : AppRole,
  'name' : string,
  'karigarName' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createUserProfile' : ActorMethod<[Principal, UserProfile], undefined>,
  'deleteOrder' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMasterDesigns' : ActorMethod<[], Array<[DesignCode, MasterDesignEntry]>>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getUnmappedDesignCodes' : ActorMethod<[], Array<UnmappedOrderEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'healthCheck' : ActorMethod<[], HealthCheckResponse>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveMasterDesigns' : ActorMethod<
    [Array<[DesignCode, MasterDesignEntry]>],
    undefined
  >,
  'setActiveFlagForMasterDesign' : ActorMethod<
    [DesignCode, boolean],
    undefined
  >,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'uploadParsedOrders' : ActorMethod<[Array<Order>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];