/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AppRole = IDL.Variant({
  'Staff' : IDL.Null,
  'Admin' : IDL.Null,
  'Karigar' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'appRole' : AppRole,
  'name' : IDL.Text,
  'karigarName' : IDL.Opt(IDL.Text),
});
export const MasterDesignEntry = IDL.Record({
  'isActive' : IDL.Bool,
  'karigarName' : IDL.Text,
  'genericName' : IDL.Text,
});
export const Time = IDL.Int;
export const Order = IDL.Record({
  'qty' : IDL.Nat,
  'weight' : IDL.Float64,
  'status' : IDL.Text,
  'createdAt' : Time,
  'size' : IDL.Float64,
  'orderType' : IDL.Text,
  'orderNo' : IDL.Text,
  'isCustomerOrder' : IDL.Bool,
  'karigarName' : IDL.Text,
  'genericName' : IDL.Text,
  'designCode' : IDL.Text,
  'uploadDate' : Time,
  'remarks' : IDL.Text,
});
export const UnmappedOrderEntry = IDL.Record({
  'qty' : IDL.Nat,
  'weight' : IDL.Float64,
  'createdAt' : Time,
  'size' : IDL.Float64,
  'orderType' : IDL.Text,
  'orderNo' : IDL.Text,
  'isCustomerOrder' : IDL.Bool,
  'designCode' : IDL.Text,
  'uploadDate' : Time,
  'remarks' : IDL.Text,
});
export const HealthCheckResponse = IDL.Record({
  'status' : IDL.Text,
  'canisterId' : IDL.Text,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createUserProfile' : IDL.Func([IDL.Principal, UserProfile], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMasterDesigns' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, MasterDesignEntry))],
      ['query'],
    ),
  'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getUnmappedDesignCodes' : IDL.Func(
      [],
      [IDL.Vec(UnmappedOrderEntry)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'healthCheck' : IDL.Func([], [HealthCheckResponse], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveMasterDesigns' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Text, MasterDesignEntry))],
      [],
      [],
    ),
  'setActiveFlagForMasterDesign' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'uploadParsedOrders' : IDL.Func([IDL.Vec(Order)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AppRole = IDL.Variant({
    'Staff' : IDL.Null,
    'Admin' : IDL.Null,
    'Karigar' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'appRole' : AppRole,
    'name' : IDL.Text,
    'karigarName' : IDL.Opt(IDL.Text),
  });
  const MasterDesignEntry = IDL.Record({
    'isActive' : IDL.Bool,
    'karigarName' : IDL.Text,
    'genericName' : IDL.Text,
  });
  const Time = IDL.Int;
  const Order = IDL.Record({
    'qty' : IDL.Nat,
    'weight' : IDL.Float64,
    'status' : IDL.Text,
    'createdAt' : Time,
    'size' : IDL.Float64,
    'orderType' : IDL.Text,
    'orderNo' : IDL.Text,
    'isCustomerOrder' : IDL.Bool,
    'karigarName' : IDL.Text,
    'genericName' : IDL.Text,
    'designCode' : IDL.Text,
    'uploadDate' : Time,
    'remarks' : IDL.Text,
  });
  const UnmappedOrderEntry = IDL.Record({
    'qty' : IDL.Nat,
    'weight' : IDL.Float64,
    'createdAt' : Time,
    'size' : IDL.Float64,
    'orderType' : IDL.Text,
    'orderNo' : IDL.Text,
    'isCustomerOrder' : IDL.Bool,
    'designCode' : IDL.Text,
    'uploadDate' : Time,
    'remarks' : IDL.Text,
  });
  const HealthCheckResponse = IDL.Record({
    'status' : IDL.Text,
    'canisterId' : IDL.Text,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createUserProfile' : IDL.Func([IDL.Principal, UserProfile], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMasterDesigns' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, MasterDesignEntry))],
        ['query'],
      ),
    'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getUnmappedDesignCodes' : IDL.Func(
        [],
        [IDL.Vec(UnmappedOrderEntry)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'healthCheck' : IDL.Func([], [HealthCheckResponse], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveMasterDesigns' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Text, MasterDesignEntry))],
        [],
        [],
      ),
    'setActiveFlagForMasterDesign' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'uploadParsedOrders' : IDL.Func([IDL.Vec(Order)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };