/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BlockUserRequest = IDL.Record({
  'user' : IDL.Principal,
  'reason' : IDL.Opt(IDL.Text),
});
export const BulkOrderUpdate = IDL.Record({
  'isReturnedFromDelivered' : IDL.Opt(IDL.Bool),
  'orderNos' : IDL.Vec(IDL.Text),
  'newStatus' : IDL.Text,
});
export const Karigar = IDL.Record({ 'name' : IDL.Text, 'isActive' : IDL.Bool });
export const AppRole = IDL.Variant({
  'Staff' : IDL.Null,
  'Admin' : IDL.Null,
  'Karigar' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'isCreated' : IDL.Bool,
  'appRole' : AppRole,
  'name' : IDL.Text,
  'karigarName' : IDL.Opt(IDL.Text),
});
export const Time = IDL.Int;
export const PersistentOrder = IDL.Record({
  'qty' : IDL.Nat,
  'weight' : IDL.Opt(IDL.Float64),
  'status' : IDL.Text,
  'createdAt' : Time,
  'size' : IDL.Opt(IDL.Float64),
  'orderType' : IDL.Text,
  'isReturnedFromDelivered' : IDL.Bool,
  'orderNo' : IDL.Text,
  'isCustomerOrder' : IDL.Bool,
  'karigarName' : IDL.Text,
  'genericName' : IDL.Text,
  'designCode' : IDL.Text,
  'uploadDate' : Time,
  'remarks' : IDL.Text,
});
export const ActivityLogEntry = IDL.Record({
  'action' : IDL.Text,
  'userId' : IDL.Principal,
  'timestamp' : Time,
  'details' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const DesignImageMapping = IDL.Record({
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'genericName' : IDL.Text,
  'image' : ExternalBlob,
  'designCode' : IDL.Text,
});
export const MasterDesignEntry = IDL.Record({
  'isActive' : IDL.Bool,
  'karigarName' : IDL.Text,
  'genericName' : IDL.Text,
});
export const UnmappedOrderEntry = IDL.Record({
  'qty' : IDL.Nat,
  'weight' : IDL.Opt(IDL.Float64),
  'createdAt' : Time,
  'size' : IDL.Opt(IDL.Float64),
  'orderType' : IDL.Text,
  'orderNo' : IDL.Text,
  'isCustomerOrder' : IDL.Bool,
  'designCode' : IDL.Text,
  'uploadDate' : Time,
  'remarks' : IDL.Text,
});
export const HallmarkReturnRequest = IDL.Record({
  'actionType' : IDL.Variant({
    'update_status' : IDL.Null,
    'return_hallmark' : IDL.Null,
  }),
  'orderNos' : IDL.Vec(IDL.Text),
});
export const HealthCheckResponse = IDL.Record({
  'status' : IDL.Text,
  'canisterId' : IDL.Text,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const PersistentKarigar = IDL.Record({
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
});
export const PartialFulfillmentQty = IDL.Record({
  'suppliedQty' : IDL.Nat,
  'orderNo' : IDL.Text,
});
export const PartialFulfillmentRequest = IDL.Record({
  'entries' : IDL.Vec(PartialFulfillmentQty),
});
export const UpdateOrderTotalSuppliedRequest = IDL.Record({
  'orderNo' : IDL.Text,
  'newTotalSupplied' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'blockUser' : IDL.Func([BlockUserRequest], [], []),
  'bulkMarkOrdersAsDelivered' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'bulkUpdateOrderStatus' : IDL.Func([BulkOrderUpdate], [], []),
  'createKarigar' : IDL.Func([Karigar], [], []),
  'createUserProfile' : IDL.Func([IDL.Principal, UserProfile], [], []),
  'deleteKarigarByName' : IDL.Func([IDL.Text], [], []),
  'getActiveOrdersForKarigar' : IDL.Func([], [IDL.Vec(PersistentOrder)], []),
  'getActivityLog' : IDL.Func([], [IDL.Vec(ActivityLogEntry)], ['query']),
  'getAdminDesignImageMappings' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(DesignImageMapping, ExternalBlob))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDesignImageMappings' : IDL.Func(
      [],
      [IDL.Vec(DesignImageMapping)],
      ['query'],
    ),
  'getMasterDesigns' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, MasterDesignEntry))],
      ['query'],
    ),
  'getOrders' : IDL.Func([], [IDL.Vec(PersistentOrder)], []),
  'getUnmappedDesignCodes' : IDL.Func(
      [],
      [IDL.Vec(UnmappedOrderEntry)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'handleHallmarkReturns' : IDL.Func([HallmarkReturnRequest], [], []),
  'healthCheck' : IDL.Func([], [HealthCheckResponse], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'isUserBlocked' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'listDistinctKarigars' : IDL.Func(
      [],
      [IDL.Vec(PersistentKarigar)],
      ['query'],
    ),
  'listKarigars' : IDL.Func([], [IDL.Vec(PersistentKarigar)], ['query']),
  'listKarigarsNames' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'listUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'markOrderAsDelivered' : IDL.Func([IDL.Text], [], []),
  'processPartialFulfillment' : IDL.Func([PartialFulfillmentRequest], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveDesignImageMappings' : IDL.Func(
      [IDL.Vec(DesignImageMapping)],
      [IDL.Vec(DesignImageMapping)],
      [],
    ),
  'saveMasterDesigns' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Text, MasterDesignEntry))],
      [],
      [],
    ),
  'setActiveFlagForMasterDesign' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'unblockUser' : IDL.Func([IDL.Principal], [], []),
  'updateOrderTotalSupplied' : IDL.Func(
      [UpdateOrderTotalSuppliedRequest],
      [],
      [],
    ),
  'updateOrdersForNewKarigar' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'uploadParsedOrders' : IDL.Func([IDL.Vec(PersistentOrder)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BlockUserRequest = IDL.Record({
    'user' : IDL.Principal,
    'reason' : IDL.Opt(IDL.Text),
  });
  const BulkOrderUpdate = IDL.Record({
    'isReturnedFromDelivered' : IDL.Opt(IDL.Bool),
    'orderNos' : IDL.Vec(IDL.Text),
    'newStatus' : IDL.Text,
  });
  const Karigar = IDL.Record({ 'name' : IDL.Text, 'isActive' : IDL.Bool });
  const AppRole = IDL.Variant({
    'Staff' : IDL.Null,
    'Admin' : IDL.Null,
    'Karigar' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'isCreated' : IDL.Bool,
    'appRole' : AppRole,
    'name' : IDL.Text,
    'karigarName' : IDL.Opt(IDL.Text),
  });
  const Time = IDL.Int;
  const PersistentOrder = IDL.Record({
    'qty' : IDL.Nat,
    'weight' : IDL.Opt(IDL.Float64),
    'status' : IDL.Text,
    'createdAt' : Time,
    'size' : IDL.Opt(IDL.Float64),
    'orderType' : IDL.Text,
    'isReturnedFromDelivered' : IDL.Bool,
    'orderNo' : IDL.Text,
    'isCustomerOrder' : IDL.Bool,
    'karigarName' : IDL.Text,
    'genericName' : IDL.Text,
    'designCode' : IDL.Text,
    'uploadDate' : Time,
    'remarks' : IDL.Text,
  });
  const ActivityLogEntry = IDL.Record({
    'action' : IDL.Text,
    'userId' : IDL.Principal,
    'timestamp' : Time,
    'details' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const DesignImageMapping = IDL.Record({
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'genericName' : IDL.Text,
    'image' : ExternalBlob,
    'designCode' : IDL.Text,
  });
  const MasterDesignEntry = IDL.Record({
    'isActive' : IDL.Bool,
    'karigarName' : IDL.Text,
    'genericName' : IDL.Text,
  });
  const UnmappedOrderEntry = IDL.Record({
    'qty' : IDL.Nat,
    'weight' : IDL.Opt(IDL.Float64),
    'createdAt' : Time,
    'size' : IDL.Opt(IDL.Float64),
    'orderType' : IDL.Text,
    'orderNo' : IDL.Text,
    'isCustomerOrder' : IDL.Bool,
    'designCode' : IDL.Text,
    'uploadDate' : Time,
    'remarks' : IDL.Text,
  });
  const HallmarkReturnRequest = IDL.Record({
    'actionType' : IDL.Variant({
      'update_status' : IDL.Null,
      'return_hallmark' : IDL.Null,
    }),
    'orderNos' : IDL.Vec(IDL.Text),
  });
  const HealthCheckResponse = IDL.Record({
    'status' : IDL.Text,
    'canisterId' : IDL.Text,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const PersistentKarigar = IDL.Record({
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
  });
  const PartialFulfillmentQty = IDL.Record({
    'suppliedQty' : IDL.Nat,
    'orderNo' : IDL.Text,
  });
  const PartialFulfillmentRequest = IDL.Record({
    'entries' : IDL.Vec(PartialFulfillmentQty),
  });
  const UpdateOrderTotalSuppliedRequest = IDL.Record({
    'orderNo' : IDL.Text,
    'newTotalSupplied' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'blockUser' : IDL.Func([BlockUserRequest], [], []),
    'bulkMarkOrdersAsDelivered' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'bulkUpdateOrderStatus' : IDL.Func([BulkOrderUpdate], [], []),
    'createKarigar' : IDL.Func([Karigar], [], []),
    'createUserProfile' : IDL.Func([IDL.Principal, UserProfile], [], []),
    'deleteKarigarByName' : IDL.Func([IDL.Text], [], []),
    'getActiveOrdersForKarigar' : IDL.Func([], [IDL.Vec(PersistentOrder)], []),
    'getActivityLog' : IDL.Func([], [IDL.Vec(ActivityLogEntry)], ['query']),
    'getAdminDesignImageMappings' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(DesignImageMapping, ExternalBlob))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDesignImageMappings' : IDL.Func(
        [],
        [IDL.Vec(DesignImageMapping)],
        ['query'],
      ),
    'getMasterDesigns' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, MasterDesignEntry))],
        ['query'],
      ),
    'getOrders' : IDL.Func([], [IDL.Vec(PersistentOrder)], []),
    'getUnmappedDesignCodes' : IDL.Func(
        [],
        [IDL.Vec(UnmappedOrderEntry)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'handleHallmarkReturns' : IDL.Func([HallmarkReturnRequest], [], []),
    'healthCheck' : IDL.Func([], [HealthCheckResponse], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'isUserBlocked' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'listDistinctKarigars' : IDL.Func(
        [],
        [IDL.Vec(PersistentKarigar)],
        ['query'],
      ),
    'listKarigars' : IDL.Func([], [IDL.Vec(PersistentKarigar)], ['query']),
    'listKarigarsNames' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'listUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'markOrderAsDelivered' : IDL.Func([IDL.Text], [], []),
    'processPartialFulfillment' : IDL.Func([PartialFulfillmentRequest], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveDesignImageMappings' : IDL.Func(
        [IDL.Vec(DesignImageMapping)],
        [IDL.Vec(DesignImageMapping)],
        [],
      ),
    'saveMasterDesigns' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Text, MasterDesignEntry))],
        [],
        [],
      ),
    'setActiveFlagForMasterDesign' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'unblockUser' : IDL.Func([IDL.Principal], [], []),
    'updateOrderTotalSupplied' : IDL.Func(
        [UpdateOrderTotalSuppliedRequest],
        [],
        [],
      ),
    'updateOrdersForNewKarigar' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'uploadParsedOrders' : IDL.Func([IDL.Vec(PersistentOrder)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };