/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface DesignImageMapping {
    createdAt: Time;
    createdBy: Principal;
    genericName: string;
    image: ExternalBlob;
    designCode: string;
}
export interface BulkOrderUpdate {
    orderNos: Array<string>;
    newStatus: string;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface HealthCheckResponse {
    status: string;
    canisterId: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface HallmarkReturnRequest {
    actionType: Variant_update_status_return_hallmark;
    orderNos: Array<string>;
}
export interface UnmappedOrderEntry {
    qty: bigint;
    weight?: number;
    createdAt: Time;
    size?: number;
    orderType: string;
    orderNo: string;
    isCustomerOrder: boolean;
    designCode: string;
    uploadDate: Time;
    remarks: string;
}
export interface PersistentKarigar {
    id: string;
    name: string;
    isActive: boolean;
}
export interface SavedMasterDesignsRequest {
    masterDesigns: Array<[string, MasterDesignEntry]>;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface ActivityLogEntry {
    action: string;
    userId: Principal;
    timestamp: Time;
    details: string;
}
export interface BlockUserRequest {
    user: Principal;
    reason?: string;
}
export interface PersistentOrder {
    qty: bigint;
    weight?: number;
    status: string;
    createdAt: Time;
    size?: number;
    orderType: string;
    orderNo: string;
    isCustomerOrder: boolean;
    genericName: string;
    designCode: string;
    uploadDate: Time;
    karigarId: string;
    remarks: string;
}
export interface UpdateOrderTotalSuppliedRequest {
    orderNo: string;
    newTotalSupplied: bigint;
}
export interface PartialFulfillmentRequest {
    entries: Array<PartialFulfillmentQty>;
}
export interface PartialFulfillmentQty {
    suppliedQty: bigint;
    orderNo: string;
}
export interface MasterDesignEntry {
    isActive: boolean;
    genericName: string;
    karigarId: string;
}
export interface UserProfile {
    isCreated: boolean;
    appRole: AppRole;
    name: string;
    karigarId?: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum AppRole {
    Staff = "Staff",
    Admin = "Admin",
    Karigar = "Karigar"
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_update_status_return_hallmark {
    update_status = "update_status",
    return_hallmark = "return_hallmark"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    blockUser(request: BlockUserRequest): Promise<void>;
    bulkMarkOrdersAsDelivered(orderNos: Array<string>): Promise<void>;
    bulkUpdateOrderStatus(bulkUpdate: BulkOrderUpdate): Promise<void>;
    createKarigar(karigar: PersistentKarigar): Promise<void>;
    createUserProfile(user: Principal, profile: UserProfile): Promise<void>;
    deleteKarigarById(karigarId: string): Promise<void>;
    getActiveOrdersForKarigar(): Promise<Array<PersistentOrder>>;
    getActivityLog(): Promise<Array<ActivityLogEntry>>;
    getAdminDesignImageMappings(): Promise<Array<[DesignImageMapping, ExternalBlob]>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDesignImageMappings(): Promise<Array<DesignImageMapping>>;
    getGivenToHallmarkOrders(): Promise<Array<PersistentOrder>>;
    getMasterDesigns(): Promise<Array<[string, MasterDesignEntry]>>;
    getOrders(): Promise<Array<PersistentOrder>>;
    getUnmappedDesignCodes(): Promise<Array<UnmappedOrderEntry>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    handleHallmarkReturns(request: HallmarkReturnRequest): Promise<void>;
    healthCheck(): Promise<HealthCheckResponse>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    isUserBlocked(user: Principal): Promise<boolean>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    listDistinctKarigars(): Promise<Array<PersistentKarigar>>;
    listKarigarReference(): Promise<Array<PersistentKarigar>>;
    listKarigars(): Promise<Array<PersistentKarigar>>;
    listUserProfiles(): Promise<Array<UserProfile>>;
    markOrderAsDelivered(orderNo: string): Promise<void>;
    processPartialFulfillment(request: PartialFulfillmentRequest): Promise<void>;
    requestApproval(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveDesignImageMappings(parsedMappings: Array<DesignImageMapping>): Promise<Array<DesignImageMapping>>;
    saveMasterDesigns(request: SavedMasterDesignsRequest): Promise<void>;
    setActiveFlagForMasterDesign(designCode: string, isActive: boolean): Promise<void>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    unblockUser(user: Principal): Promise<void>;
    updateOrderTotalSupplied(request: UpdateOrderTotalSuppliedRequest): Promise<void>;
    updateOrdersForNewKarigar(designCode: string, newKarigarId: string): Promise<void>;
    uploadParsedOrders(parsedOrders: Array<PersistentOrder>): Promise<void>;
}
import type { AppRole as _AppRole, ApprovalStatus as _ApprovalStatus, BlockUserRequest as _BlockUserRequest, DesignImageMapping as _DesignImageMapping, ExternalBlob as _ExternalBlob, HallmarkReturnRequest as _HallmarkReturnRequest, PersistentOrder as _PersistentOrder, Time as _Time, UnmappedOrderEntry as _UnmappedOrderEntry, UserApprovalInfo as _UserApprovalInfo, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async blockUser(arg0: BlockUserRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.blockUser(to_candid_BlockUserRequest_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.blockUser(to_candid_BlockUserRequest_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async bulkMarkOrdersAsDelivered(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkMarkOrdersAsDelivered(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkMarkOrdersAsDelivered(arg0);
            return result;
        }
    }
    async bulkUpdateOrderStatus(arg0: BulkOrderUpdate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkUpdateOrderStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkUpdateOrderStatus(arg0);
            return result;
        }
    }
    async createKarigar(arg0: PersistentKarigar): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createKarigar(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createKarigar(arg0);
            return result;
        }
    }
    async createUserProfile(arg0: Principal, arg1: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createUserProfile(arg0, to_candid_UserProfile_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUserProfile(arg0, to_candid_UserProfile_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteKarigarById(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteKarigarById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteKarigarById(arg0);
            return result;
        }
    }
    async getActiveOrdersForKarigar(): Promise<Array<PersistentOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveOrdersForKarigar();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveOrdersForKarigar();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActivityLog(): Promise<Array<ActivityLogEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivityLog();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivityLog();
            return result;
        }
    }
    async getAdminDesignImageMappings(): Promise<Array<[DesignImageMapping, ExternalBlob]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminDesignImageMappings();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminDesignImageMappings();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDesignImageMappings(): Promise<Array<DesignImageMapping>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDesignImageMappings();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDesignImageMappings();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGivenToHallmarkOrders(): Promise<Array<PersistentOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGivenToHallmarkOrders();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGivenToHallmarkOrders();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMasterDesigns(): Promise<Array<[string, MasterDesignEntry]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMasterDesigns();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMasterDesigns();
            return result;
        }
    }
    async getOrders(): Promise<Array<PersistentOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrders();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrders();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUnmappedDesignCodes(): Promise<Array<UnmappedOrderEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnmappedDesignCodes();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnmappedDesignCodes();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async handleHallmarkReturns(arg0: HallmarkReturnRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.handleHallmarkReturns(to_candid_HallmarkReturnRequest_n37(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.handleHallmarkReturns(to_candid_HallmarkReturnRequest_n37(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async healthCheck(): Promise<HealthCheckResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.healthCheck();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.healthCheck();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async isUserBlocked(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isUserBlocked(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isUserBlocked(arg0);
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async listDistinctKarigars(): Promise<Array<PersistentKarigar>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDistinctKarigars();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDistinctKarigars();
            return result;
        }
    }
    async listKarigarReference(): Promise<Array<PersistentKarigar>> {
        if (this.processError) {
            try {
                const result = await this.actor.listKarigarReference();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listKarigarReference();
            return result;
        }
    }
    async listKarigars(): Promise<Array<PersistentKarigar>> {
        if (this.processError) {
            try {
                const result = await this.actor.listKarigars();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listKarigars();
            return result;
        }
    }
    async listUserProfiles(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUserProfiles();
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUserProfiles();
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async markOrderAsDelivered(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markOrderAsDelivered(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markOrderAsDelivered(arg0);
            return result;
        }
    }
    async processPartialFulfillment(arg0: PartialFulfillmentRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.processPartialFulfillment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.processPartialFulfillment(arg0);
            return result;
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveDesignImageMappings(arg0: Array<DesignImageMapping>): Promise<Array<DesignImageMapping>> {
        if (this.processError) {
            try {
                const result = await this.actor.saveDesignImageMappings(await to_candid_vec_n46(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveDesignImageMappings(await to_candid_vec_n46(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveMasterDesigns(arg0: SavedMasterDesignsRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveMasterDesigns(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveMasterDesigns(arg0);
            return result;
        }
    }
    async setActiveFlagForMasterDesign(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setActiveFlagForMasterDesign(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setActiveFlagForMasterDesign(arg0, arg1);
            return result;
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n50(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n50(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async unblockUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unblockUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unblockUser(arg0);
            return result;
        }
    }
    async updateOrderTotalSupplied(arg0: UpdateOrderTotalSuppliedRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderTotalSupplied(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderTotalSupplied(arg0);
            return result;
        }
    }
    async updateOrdersForNewKarigar(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrdersForNewKarigar(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrdersForNewKarigar(arg0, arg1);
            return result;
        }
    }
    async uploadParsedOrders(arg0: Array<PersistentOrder>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadParsedOrders(to_candid_vec_n52(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadParsedOrders(to_candid_vec_n52(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_AppRole_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppRole): AppRole {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_ApprovalStatus_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
async function from_candid_DesignImageMapping_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DesignImageMapping): Promise<DesignImageMapping> {
    return await from_candid_record_n23(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_PersistentOrder_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PersistentOrder): PersistentOrder {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UnmappedOrderEntry_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UnmappedOrderEntry): UnmappedOrderEntry {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    qty: bigint;
    weight: [] | [number];
    status: string;
    createdAt: _Time;
    size: [] | [number];
    orderType: string;
    orderNo: string;
    isCustomerOrder: boolean;
    genericName: string;
    designCode: string;
    uploadDate: _Time;
    karigarId: string;
    remarks: string;
}): {
    qty: bigint;
    weight?: number;
    status: string;
    createdAt: Time;
    size?: number;
    orderType: string;
    orderNo: string;
    isCustomerOrder: boolean;
    genericName: string;
    designCode: string;
    uploadDate: Time;
    karigarId: string;
    remarks: string;
} {
    return {
        qty: value.qty,
        weight: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.weight)),
        status: value.status,
        createdAt: value.createdAt,
        size: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.size)),
        orderType: value.orderType,
        orderNo: value.orderNo,
        isCustomerOrder: value.isCustomerOrder,
        genericName: value.genericName,
        designCode: value.designCode,
        uploadDate: value.uploadDate,
        karigarId: value.karigarId,
        remarks: value.remarks
    };
}
async function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    createdAt: _Time;
    createdBy: Principal;
    genericName: string;
    image: _ExternalBlob;
    designCode: string;
}): Promise<{
    createdAt: Time;
    createdBy: Principal;
    genericName: string;
    image: ExternalBlob;
    designCode: string;
}> {
    return {
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        genericName: value.genericName,
        image: await from_candid_ExternalBlob_n24(_uploadFile, _downloadFile, value.image),
        designCode: value.designCode
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isCreated: boolean;
    appRole: _AppRole;
    name: string;
    karigarId: [] | [string];
}): {
    isCreated: boolean;
    appRole: AppRole;
    name: string;
    karigarId?: string;
} {
    return {
        isCreated: value.isCreated,
        appRole: from_candid_AppRole_n28(_uploadFile, _downloadFile, value.appRole),
        name: value.name,
        karigarId: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.karigarId))
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    qty: bigint;
    weight: [] | [number];
    createdAt: _Time;
    size: [] | [number];
    orderType: string;
    orderNo: string;
    isCustomerOrder: boolean;
    designCode: string;
    uploadDate: _Time;
    remarks: string;
}): {
    qty: bigint;
    weight?: number;
    createdAt: Time;
    size?: number;
    orderType: string;
    orderNo: string;
    isCustomerOrder: boolean;
    designCode: string;
    uploadDate: Time;
    remarks: string;
} {
    return {
        qty: value.qty,
        weight: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.weight)),
        createdAt: value.createdAt,
        size: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.size)),
        orderType: value.orderType,
        orderNo: value.orderNo,
        isCustomerOrder: value.isCustomerOrder,
        designCode: value.designCode,
        uploadDate: value.uploadDate,
        remarks: value.remarks
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n43(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_tuple_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_DesignImageMapping, _ExternalBlob]): Promise<[DesignImageMapping, ExternalBlob]> {
    return [
        await from_candid_DesignImageMapping_n22(_uploadFile, _downloadFile, value[0]),
        await from_candid_ExternalBlob_n24(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Staff: null;
} | {
    Admin: null;
} | {
    Karigar: null;
}): AppRole {
    return "Staff" in value ? AppRole.Staff : "Admin" in value ? AppRole.Admin : "Karigar" in value ? AppRole.Karigar : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PersistentOrder>): Array<PersistentOrder> {
    return value.map((x)=>from_candid_PersistentOrder_n17(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_DesignImageMapping, _ExternalBlob]>): Promise<Array<[DesignImageMapping, ExternalBlob]>> {
    return await Promise.all(value.map(async (x)=>await from_candid_tuple_n21(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DesignImageMapping>): Promise<Array<DesignImageMapping>> {
    return await Promise.all(value.map(async (x)=>await from_candid_DesignImageMapping_n22(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UnmappedOrderEntry>): Array<UnmappedOrderEntry> {
    return value.map((x)=>from_candid_UnmappedOrderEntry_n35(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n41(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n26(_uploadFile, _downloadFile, x));
}
function to_candid_AppRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppRole): _AppRole {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_ApprovalStatus_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function to_candid_BlockUserRequest_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BlockUserRequest): _BlockUserRequest {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
async function to_candid_DesignImageMapping_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DesignImageMapping): Promise<_DesignImageMapping> {
    return await to_candid_record_n48(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_HallmarkReturnRequest_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HallmarkReturnRequest): _HallmarkReturnRequest {
    return to_candid_record_n38(_uploadFile, _downloadFile, value);
}
function to_candid_PersistentOrder_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PersistentOrder): _PersistentOrder {
    return to_candid_record_n54(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    user: Principal;
    reason?: string;
}): {
    user: Principal;
    reason: [] | [string];
} {
    return {
        user: value.user,
        reason: value.reason ? candid_some(value.reason) : candid_none()
    };
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isCreated: boolean;
    appRole: AppRole;
    name: string;
    karigarId?: string;
}): {
    isCreated: boolean;
    appRole: _AppRole;
    name: string;
    karigarId: [] | [string];
} {
    return {
        isCreated: value.isCreated,
        appRole: to_candid_AppRole_n14(_uploadFile, _downloadFile, value.appRole),
        name: value.name,
        karigarId: value.karigarId ? candid_some(value.karigarId) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    actionType: Variant_update_status_return_hallmark;
    orderNos: Array<string>;
}): {
    actionType: {
        update_status: null;
    } | {
        return_hallmark: null;
    };
    orderNos: Array<string>;
} {
    return {
        actionType: to_candid_variant_n39(_uploadFile, _downloadFile, value.actionType),
        orderNos: value.orderNos
    };
}
async function to_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    createdAt: Time;
    createdBy: Principal;
    genericName: string;
    image: ExternalBlob;
    designCode: string;
}): Promise<{
    createdAt: _Time;
    createdBy: Principal;
    genericName: string;
    image: _ExternalBlob;
    designCode: string;
}> {
    return {
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        genericName: value.genericName,
        image: await to_candid_ExternalBlob_n49(_uploadFile, _downloadFile, value.image),
        designCode: value.designCode
    };
}
function to_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    qty: bigint;
    weight?: number;
    status: string;
    createdAt: Time;
    size?: number;
    orderType: string;
    orderNo: string;
    isCustomerOrder: boolean;
    genericName: string;
    designCode: string;
    uploadDate: Time;
    karigarId: string;
    remarks: string;
}): {
    qty: bigint;
    weight: [] | [number];
    status: string;
    createdAt: _Time;
    size: [] | [number];
    orderType: string;
    orderNo: string;
    isCustomerOrder: boolean;
    genericName: string;
    designCode: string;
    uploadDate: _Time;
    karigarId: string;
    remarks: string;
} {
    return {
        qty: value.qty,
        weight: value.weight ? candid_some(value.weight) : candid_none(),
        status: value.status,
        createdAt: value.createdAt,
        size: value.size ? candid_some(value.size) : candid_none(),
        orderType: value.orderType,
        orderNo: value.orderNo,
        isCustomerOrder: value.isCustomerOrder,
        genericName: value.genericName,
        designCode: value.designCode,
        uploadDate: value.uploadDate,
        karigarId: value.karigarId,
        remarks: value.remarks
    };
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppRole): {
    Staff: null;
} | {
    Admin: null;
} | {
    Karigar: null;
} {
    return value == AppRole.Staff ? {
        Staff: null
    } : value == AppRole.Admin ? {
        Admin: null
    } : value == AppRole.Karigar ? {
        Karigar: null
    } : value;
}
function to_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_update_status_return_hallmark): {
    update_status: null;
} | {
    return_hallmark: null;
} {
    return value == Variant_update_status_return_hallmark.update_status ? {
        update_status: null
    } : value == Variant_update_status_return_hallmark.return_hallmark ? {
        return_hallmark: null
    } : value;
}
function to_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<DesignImageMapping>): Promise<Array<_DesignImageMapping>> {
    return await Promise.all(value.map(async (x)=>await to_candid_DesignImageMapping_n47(_uploadFile, _downloadFile, x)));
}
function to_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<PersistentOrder>): Array<_PersistentOrder> {
    return value.map((x)=>to_candid_PersistentOrder_n53(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
